### ISSUE TITLE
Test on a "production" database

### ISSUE THREAD

**Issue by bear454** [openSUSE/osem#2256]
**I'm submitting a ..**
- [ ] Bug Report
- [x] Feature Request

**Current behavior:**

Continuous testing on Travis CI is run on a Sqlite3 database; as of filing this issue, running our test suite on either MariaDB or Postgres results in intermittent failures.

**Expected correct behavior:**

Travis CI runs on either MariaDB or Postgres, without introducing flakiness.

**Other information:**

Introduced in #2225.

**Comment by Ana06** [comment]
@bear454 we could run travis twice with a different database. Would you like to set this up? You would need to fix the failures, but after that we would ensure that this keep working in every PR. :thinking:

**Comment by hennevogel** [comment]
@Ana06 read the discussion in #2225

**Comment by AndrewKvalheim** [comment]
Tests are passing reliably for me on PostgreSQL after merging:

- [x] Decouple tests from unspecified data ordering #2650, #2652
- [x] Fix access to the version history of organization-level roles #2654
- [x] Fix bug in UserDatatable query affecting PostgreSQL #2656
- [x] Use Rails transactional tests #2659
- [x] Fix bug in test of animated form #2662
