### ISSUE TITLE
BigGoals tracking

### ISSUE THREAD

**Issue by kalabiyau** [openSUSE/osem#362]
- [x] establish a place for brainstorming of BigGoals
- [ ] cleanup README, move installation to separate md file
- [ ] collect brainstormed ideas to wiki
- [ ] on milestone 2 planning, choose 3-5 BigGoals for next calendar year
