### ISSUE TITLE
Implement ticket payment feature

### ISSUE THREAD

**Issue by rishabhs95** [openSUSE/osem#969]
Deliverables : 
- [x] Proper documentation and tests for all deliverables
- [x] Define payment state machine transitions
- [x] Integrate Stripe payment gateway through ActiveMerchant library
- [x] Appropriate notifications updates for payments
- [x] ~~Persist user payment preferences~~
- [x] Update admin views to check payment status

**Comment by Ana06** [comment]
Is this already done? Can it be closed?

**Comment by rishabhs95** [comment]
Yeah @Ana06, I'm closing this issue as all the sub-tasks were completed.
